name: mlatu
version: 0.1.0.0
synopsis: Mlatu programming language
category: Language
author: Caden Haustein
maintainer: code@brightlysalty.33mail.com
github: brightly-salty/mlatu
license-file: LICENSE.md

ghc-options:
  - -Wall

default-extensions:
  - NoImplicitPrelude
  - LambdaCase
  - OverloadedStrings
  #  - GHC2021
  - EmptyCase
  - PostfixOperators
  - TupleSections
  - ImportQualifiedPost
  - NamedFieldPuns
  - BangPatterns
  - BinaryLiterals
  - HexFloatLiterals
  - NumericUnderscores
  - GADTSyntax
  - RankNTypes
  - TypeApplications
  - PolyKinds
  - StandaloneKindSignatures
  - ExistentialQuantification
  - TypeOperators
  - ConstraintKinds
  - ExplicitForAll
  - KindSignatures
  - NamedWildCards
  - ScopedTypeVariables
  - FlexibleContexts
  - FlexibleInstances
  - MultiParamTypeClasses
  - ConstrainedClassMethods
  - InstanceSigs
  - TypeSynonymInstances
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveTraversable
  - StandaloneDeriving
  - EmptyDataDeriving
  - DeriveLift
  - GeneralizedNewtypeDeriving
  - DeriveGeneric

dependencies:
  - base >=4.8
  - bytestring
  - containers
  - file-embed
  - monad-loops
  - optics
  - parsec
  - prettyprinter
  - relude ==0.7.0.0
  - text
  - transformers
  - unordered-containers

library:
  source-dirs: src
  when:
    - condition: false
      other-modules: Paths_name

executables:
  mlatu:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -O2
    dependencies:
      - directory
      - repline
      - exceptions
      - optparse-applicative
      - typed-process
      - mlatu

tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - HUnit
      - hspec
      - knob
      - mlatu
